class ContractName:
    REGISTRY = 'ContractRegistry'
    GNFT_TOKEN = 'GNFTToken'
    LIFE_TOKEN = 'LIFEToken'
    LIFE_TREASURY = 'LIFETreasury'
    GENE_FRIEND_NETWORK_WALLET = 'GeneFriendNetworkWallet'
    GENETIC_PROFILE_OWNER_WALLET = 'GeneticProfileOwnerWallet'
    INVESTOR_WALLET = 'InvestorWallet'
    LAB_SERVICE_PROVIDER_WALLET = 'LabServiceProviderWallet'
    REPORT_SERVICE_PROVIDER_WALLET = 'ReportServiceProviderWallet'
    DATA_UTILIZER_WALLET = 'DataUtilizerWallet'
