project_structure:
  build: build
  contracts: contracts
  interfaces: interfaces
  reports: reports
  scripts: scripts
  tests: tests

networks:
  default: development
  development:
    gas_limit: max
    gas_buffer: 1
    gas_price: 0
    max_fee: null
    priority_fee: null
    reverting_tx_gas_limit: max
    default_contract_owner: true
    cmd_settings: null
  avax-fuji:
    gas_limit: max
    gas_buffer: 1
    gas_price: 0
    max_fee: null
    priority_fee: null
    reverting_tx_gas_limit: max
    default_contract_owner: true
    cmd_settings: null
    explorer: https://testnet.snowtrace.io/

  live:
    gas_limit: auto
    gas_buffer: 1.1
    gas_price: auto
    max_fee: null
    priority_fee: null
    reverting_tx_gas_limit: false
    default_contract_owner: false

compiler:
  solc:
    version: null
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1"
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.1
